apiVersion: v1
kind: ConfigMap
metadata:
  name: ckn-config
  namespace: ckn
data:
  neo4j-uri: "bolt://neo4j:7687"
  patra-server: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ckn-secrets
  namespace: ckn
type: Opaque
stringData:
  neo4j-user: "neo4j"
  neo4j-password: "PWD_HERE"  # Change this in production!
  openai-api-key: ""
