name: CKN-CI

on:
  push:
    branches: [ main, release/1.0.0 ]
  pull_request:
    branches: [ main, release/1.0.0 ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install CKN Oracle Daemon plugin dependencies
        run: |
          pip install -r plugins/oracle_ckn_daemon/requirements.txt
          pip install -r plugins/oracle_ckn_daemon/tests/requirements.txt

      - name: Test CKN Oracle Daemon plugin
        run: |
          pytest plugins/oracle_ckn_daemon/tests/ -v
